uid = "27de7a0f-16d2-26c3-ac46-904a094e21ffb93d65db"
api_version = "2025-07"
[[extensions]]
name = "Thank You Upsell"
handle = "thankyou-upsell"
type = "ui_extension"

[[extensions.targeting]]
target = "purchase.thank-you.block.render"
module = "./src/index.tsx"
