query Input {
  cart {
    _custom_store: attribute(key: "_custom_store") {
     value
    }
    lines {
      id
      quantity
      attribute(key: "automatic_discount") {
        key
        value
      }
      _compare_price: attribute(key: "_DD_compare_price") {
        value
      }
      subscription_evrgreen: attribute(key: "_subscription_evrgreen") {
        value
      }
      cost {
        amountPerQuantity {
          amount
        }
      }

      merchandise {
        __typename
        ...on ProductVariant {
          id
        }
      }
    }
  }
  discountNode {
    metafield(namespace: "$app:volume-discount", key: "function-configuration") {
      value
    }
  }
}

